---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-ngx
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: volsync
    - name: cloudnative-pg
    - name: dragonfly-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/selfhosted/paperless-ngx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
