---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-ngx
  namespace: &namespace selfhosted
spec:
  targetNamespace: *namespace
  components:
    - ../../../../flux/components/volsync
  dependsOn:
    - name: volsync
      namespace: storage
    - name: cloudnative-pg
      namespace: database
    - name: dragonfly-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/selfhosted/paperless-ngx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
