---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafana.yaml
  - ./grafanadatasource.yaml
  - ./grafanadashboard.yaml
  - ./grafanadashboard-configmap.yaml
  - ./servicemonitor.yaml
  - ./httproute.yaml
configMapGenerator:
  - name: grafana-dashboard-media-storage
    files:
      - media-storage.json=dashboards/media-storage.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-k8s-cluster
    files:
      - k8s-cluster.json=dashboards/k8s-cluster.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-flux
    files:
      - flux.json=dashboards/flux.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-ingress-nginx
    files:
      - ingress-nginx.json=dashboards/ingress-nginx.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-alert-history
    files:
      - alert-history.json=dashboards/alert-history.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-alerting-health
    files:
      - alerting-health.json=dashboards/alerting-health.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-snmp-network
    files:
      - snmp-network.json=dashboards/snmp-network.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-snmp-switch-ports
    files:
      - snmp-switch-ports.json=dashboards/snmp-switch-ports.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-snmp-fabric-overview
    files:
      - snmp-fabric-overview.json=dashboards/snmp-fabric-overview.json
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-snmp-all-switches
    files:
      - snmp-all-switches.json=dashboards/snmp-all-switches.json
    options:
      disableNameSuffixHash: true
