---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../flux/components/alerts
  - ../../flux/components/namespace
  - ../../flux/components/sops
  - ../../flux/components/substitutions
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
  - ./gpu_plugins/nvidia-device-plugin/ks.yaml
  - ./gpu_plugins/intel-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reflector/ks.yaml
