---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/gatus/external
    - ../../../../flux/components/volsync
  dependsOn:
    - name: volsync
      namespace: storage
    - name: multus-config
      namespace: network
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/home-automation/home-assistant/app # redeploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: hass
      GATUS_DOMAIN: ${SECRET_DOMAIN}
      VOLSYNC_CAPACITY: 10Gi
