---
originRequest:
  noTLSVerify: true

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443

  - hostname: "${SECRET_DOMAIN_MEDIA}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_MEDIA}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443

  - hostname: "${SECRET_DOMAIN_PERSONAL}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_PERSONAL}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443

  - hostname: "${SECRET_DOMAIN_DIVING}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_DIVING}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443

  - hostname: "${SECRET_DOMAIN_WIFE}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN_WIFE}"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443

  - service: http_status:404
