libraries: # This is called out once within the config.yml file
  4k-Movies:
    run_order:
      - collections
      - metadata
      - operations
      - overlays
    collection_files:
      # - file: config/Pre-rolls.yml #Mounted by Kustomization
      - repo: Movies.yml
      - repo: Movies - Holidays by Drazzizzi.yml
      - repo: Movies - Trakt (Unplayed) by Magic815.yml
      - default: basic
      - default: imdb
    overlay_files:
      - remove_overlays: false
      - repo: Movies - Overlays - Charts.yml
      - repo: Movies - Overlays - Oscars.yml
      - repo: Movies - Overlays - Ratings.yml
      - repo: Movies - Overlays - Stand-up.yml
      - repo: Movies - Overlays - Streaming Services.yml
      - repo: Movies - Overlays - Studios.yml
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb
      delete_collections:
        configured: false
        managed: true
    minimum_items: 2
    radarr:
      url: http://radarr-uhd.media
      token: <<RADARR_UHD_API_KEY>>
      add_missing: false
      add_existing: true
      root_folder_path: "/media/baby_plex/movies-4k"
      monitor: true
      monitor_existing: true
      ignore_cache: false
      availability: announced
      quality_profile: UHD Bluray + WEB
      tag:
      search: false
      radarr_path:
      plex_path:
      upgrade_existing: false

  Movies:
    run_order:
      - collections
      - metadata
      - operations
      - overlays
    collection_files:
      # - file: config/Pre-rolls.yml #Mounted by Kustomization
      - repo: Movies.yml
      - repo: Movies - Holidays by Drazzizzi.yml
      - repo: Movies - Trakt (Unplayed) by Magic815.yml
      - default: basic
      - default: imdb
    overlay_files:
      - remove_overlays: false
      - repo: Movies - Overlays - Charts.yml
      - repo: Movies - Overlays - Oscars.yml
      - repo: Movies - Overlays - Ratings.yml
      - repo: Movies - Overlays - Stand-up.yml
      - repo: Movies - Overlays - Streaming Services.yml
      - repo: Movies - Overlays - Studios.yml
    operations:
      mass_genre_update: imdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb
      delete_collections:
        configured: false
        managed: true
    minimum_items: 2
    radarr:
      url: http://radarr.media
      token: <<RADARR_API_KEY>>
      add_missing: false
      add_existing: true
      root_folder_path: "/media/baby_plex/Movies"
      monitor: true
      monitor_existing: true
      ignore_cache: false
      availability: announced
      quality_profile: HD Bluray + WEB
      tag:
      search: false
      radarr_path:
      plex_path:
      upgrade_existing: false

  4k-TV Shows:
    collection_files:
      - repo: TV Shows.yml
      - pmm: basic
      - pmm: imdb
    overlay_files:
      - remove_overlays: false
      - repo: TV Shows - Overlays - Charts.yml
      - repo: TV Shows - Overlays - Networks.yml
      - repo: TV Shows - Overlays - Ratings.yml
      - repo: TV Shows - Overlays - Statuses.yml
      - repo: TV Shows - Overlays - Streaming Services.yml
      - repo: TV Shows - Overlays - Studios.yml
    minimum_items: 2
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb
      mass_episode_audience_rating_update: mdb_tomatoesaudience
      mass_episode_critic_rating_update: mdb_metacritic
      mass_episode_user_rating_update: imdb
      delete_collections:
        configured: false
        managed: true
    sonarr:
      url: http://sonarr-uhd.media
      token: <<SONARR_UHD_API_KEY>>
      add_missing: false
      add_existing: true
      root_folder_path: "/media/baby_plex/tv-4k"
      monitor: all
      quality_profile: WEB-2160p
      language_profile: English
      series_type: standard
      season_folder: true
      tag:
      search: false
      cutoff_search: false
      sonarr_path:
      plex_path:
      upgrade_existing: false

  TV Shows:
    collection_files:
      - repo: TV Shows.yml
      - pmm: basic
      - pmm: imdb
    overlay_files:
      - remove_overlays: false
      - repo: TV Shows - Overlays - Charts.yml
      - repo: TV Shows - Overlays - Networks.yml
      - repo: TV Shows - Overlays - Ratings.yml
      - repo: TV Shows - Overlays - Statuses.yml
      - repo: TV Shows - Overlays - Streaming Services.yml
      - repo: TV Shows - Overlays - Studios.yml
    minimum_items: 2
    operations:
      mass_genre_update: tmdb
      mass_content_rating_update: omdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_metacritic
      mass_user_rating_update: imdb
      mass_episode_audience_rating_update: mdb_tomatoesaudience
      mass_episode_critic_rating_update: mdb_metacritic
      mass_episode_user_rating_update: imdb
      delete_collections:
        configured: false
        managed: true
    sonarr:
      url: http://sonarr.media
      token: <<SONARR_API_KEY>>
      add_missing: false
      add_existing: true
      root_folder_path: "/media/baby_plex/Shows"
      monitor: all
      quality_profile: WEB-1080p
      language_profile: English
      series_type: standard
      season_folder: true
      tag:
      search: false
      cutoff_search: false
      sonarr_path:
      plex_path:
      upgrade_existing: false

settings:
  cache: true
  cache_expiration: 60
  asset_directory: /assets
  asset_folders: true
  create_asset_folders: true
  asset_depth: 0
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  missing_path: /config/missing
  custom_repo: https://github.com/DapperDivers/dapper-cluster/tree/main/kubernetes/apps/media/kometa/app/custom/
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  only_filter_missing: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
    run_order:
    - operations
    - metadata
    - collections
    - overlays
  overlay_artwork_quality: 75
  overlay_artwork_filetype: jpg
  playlist_report: false
  verify_ssl: true
  check_nightly: false
  show_unconfigured: true

plex:
  url: http://plex.media:32400
  token: <<PLEX_API_KEY>>
  timeout: 60
  db_cache: 4096
  clean_bundles: true
  empty_trash: true
  optimize: false

tmdb: # REQUIRED for the script to run
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:

tautulli:
  url: http://tautulli.media
  apikey: <<TAUTULLI_API_KEY>>

omdb:
  apikey: <<OMDB_API_KEY>>
  cache_expiration: 60

mdblist:
  apikey: <<MDBLIST_API_KEY>>
  cache_expiration: 60

trakt:
  client_id: <<TRAKT_CLIENT_ID>>
  client_secret: <<TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<TRAKT_ACCESS_TOKEN>>
    token_type: Bearer
    expires_in: <<TRAKT_EXPIRES_IN>>
    refresh_token: <<TRAKT_REFRESH_TOKEN>>
    scope: public
    created_at: <<TRAKT_CREATED_AT>>
  pin:
# notifiarr:
#   API_KEY: <<NOTIFIARR_API_KEY>>
