apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+ArbOdiu1+JWju+1VsfoQKZ0B0DEQzi/kfiwPNXKqNE=,iv:fWGyoiMBUVyUg2oGcuWXoDHlA8rvAjPw2SxUv/3cwFg=,tag:mPOVfQWOO1OOv/1Jv/VUow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TzQ4bGg4amYrV0FuM2F0
            TTNoT0daMVkvdk93Vm9UUmYwc2ZYRTk4aW44ClQ2RW96bUxlZitHbjBjRzVwVmNB
            ZmVPbUpsY3F5aHRkVmZOaEpzWlJPL3MKLS0tIHEwV3ZwNHlwcTVVMkdyenFIN2o1
            LzIwcklaRWlxTVduR1JrNTFUaWNZTDgKPuHjgPunhCUWZXXaEh+cf5lB3TH4z7fo
            ezZ9z3s5nazcp1gDmJDFK3WnVjmyZ4mSRBdul8QnDqjjpROLGOnVHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T14:43:53Z"
    mac: ENC[AES256_GCM,data:tBpEmfJQuduff80a6JurCMgTbiOGybB0+aHNKiDSHI983C427EIYW0Hl/PEtVMggxz29HLDeWpMnC1C39qmVagq1uxB0Dc8vqQr+tZhnKBUfqj7n3KokL2a5aTgXMQZwGjmdZe/YT2p83noReUgS45FXkV3F6P2VRZ+laj4nhrs=,iv:iZKW2y2bMx0FgTC+hTCCpKWIUJ7TFjuM6cBLX2nlzj8=,tag:Dc3xfIz/aHuD6BmlbT3+Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
