# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:pGbJw9iR5UTeHokG8PEhfJI0yEb3CiICoaBu9irPa1cngVih,iv:qLyngkdkY557r8Dv7/U+sK1F6osLc8opY4/VDCLqM44=,tag:kWOV/x8NUIyGmJR896s9IQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:5MWdUoa7o9T/kwLoYzw+ZAI95G/qG8GnlFukdjLGUHxrTv0kSvhEqbCMuJjNjC5OjosKSYNYmbjKmVJBGasdvyDp0dSGJHYe+NQSJSgjgFSXslmjkfK9ERPPVZbq5wtCWOfmPRSvVR79VBzkHXZCAL3HY7pdR3HaeIgSSL3+BTlgJA1zGtmd/cLeMDxFWFyKnfnid1NN2tZELqVzY/JJ59LF+Tdsil/iNd0vWzJCpg==,iv:n9zYcRZiWmeCbwJzLw2VmyCLH2F7IUiYySNh+f+cwmM=,tag:V2CLBxviayh11dnxxIgHJQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbU9hVGI5VkRDMUNheVRo
        TjVPbExvZ1JSVWNNZm1DVTYwVDdtd0JCREN3Ck5COVVtK0JORnp5SnBUN0dsd1BQ
        SkFjZE10aEVJbGNzQktBZWNDRGViL0kKLS0tIGtKL2g1Nk9sU0daUnJFVzAzT1dF
        K3p2c3NhVmYzdVJoVTB1UC9HcjVjdkUK/lZguv6Pkpeo/ZNspynakMRiBUFLHZyn
        Wuf+9y2nU68CYsxtewLNxcHH9L2SxD9qWX7qPblh4pkr6N20HIX+8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-04T17:25:36Z"
  mac: ENC[AES256_GCM,data:wW5L0Fgi6koBaVmCPZzwbyFYUCctezk73p5xDT2rw9X8rEtUt6sjYapdadFkYPAQPKnkbtU6I6QpxiqUxZrUdghq1yJhK7QPusJ1yNhCzZ4Ju4BEFvGRu0Dyzmf55C+wUmWZqZXIphOMf51mQNuuTT/4TUq3jmrHpU1Ykr237fo=,iv:6kXe3KvFb0Kka8cmb6ouC/8EzNyyfnpTkHfiXXSdSug=,tag:ikgASwZuvxLiCqTNv0mD0w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
