---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN/./-}-staging-tls
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: staging # "dev", "staging", "prod", etc..
        secretsPath: "Certificates/${SECRET_DOMAIN/./-}" # Root is "/"

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN/./-}-staging-tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
