---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${SECRET_DOMAIN/./-}-staging-tls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: "${SECRET_DOMAIN/./-}-staging-tls"
  dataFrom:
    - find:
        path: Certificates/${SECRET_DOMAIN/./-}
        name:
          regexp: tls.crt
    - find:
        path: Certificates/${SECRET_DOMAIN/./-}
        name:
          regexp: tls.key
