---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN/./-}tls
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project sluSECRET_DOMAINg
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN/./-}"

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN/./-}tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true

---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN_MEDIA/./-}tls
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN_MEDIA/./-}"

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN_MEDIA/./-}tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true

---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN_PERSONAL/./-}tls
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN_PERSONAL/./-}"

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN_PERSONAL/./-}tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true

---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN_DIVING/./-}tls
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN_DIVING/./-}"

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN_DIVING/./-}tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true


---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN_WIFE/./-}tls
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 1
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
      secretsScope:
        projectSlug: homelab-p-iqd # <-- project slug
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/Certificates/${SECRET_DOMAIN_WIFE/./-}"

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN_WIFE/./-}tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
