---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ${SECRET_DOMAIN/./-}-staging-tls
  labels:
    label-to-be-passed-to-managed-secret: infisical
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infiscal-auth-secret
        secretNamespace: external-secrets
        secretsScope: staging

  managedKubeSecretReferences:
    - secretName: ${SECRET_DOMAIN/./-}-staging-tls
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          tls.crt: "/Certificates/${SECRET_DOMAIN/./-}/tls.crt"
          tls.key: "/Certificates/${SECRET_DOMAIN/./-}/tls.key"

