---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  dependsOn:
    - name: node-feature-discovery
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.16.2
      sourceRef:
        kind: HelmRepository
        name: nvidia-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.16.2
    nodeSelector:
      nvidia.feature.node.kubernetes.io/gpu: "true"
    runtimeClassName: nvidia
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/pci-0302_10de.present
                  operator: In
                  values:
                    - "true"
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: none
          sharing:
            timeSlicing:
              renameByDefault: false
              failRequestsGreaterThanOne: false
              resources:
                - name: nvidia.com/gpu
                  replicas: 6
