---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: posterizarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: posterizarr-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        POSTERIZARR__ApiPart__FanartTvAPIKey: "{{ .FANARTTV_API_KEY }}"
        POSTERIZARR__ApiPart__PlexToken: "{{ .PLEX_TOKEN }}"
        POSTERIZARR__ApiPart__tmdbtoken: "{{ .TMDB_READ_API_TOKEN }}"
        POSTERIZARR__ApiPart__tvdbapi: "{{ .TVDB_API_KEY }}"

  dataFrom:
    - find:
        path: TMDB_READ_API_TOKEN
    - find:
        path: PLEX_TOKEN
    - find:
        path: FANARTTV_API_KEY
    - find:
        path: TVDB_API_KEY


