# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app posterizarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      posterizarr:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "0 */1 * * *"
          timeZone: &timezone ${TIME_ZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/fscorrupt/docker-posterizarr
              tag: latest@sha256:bf0ca036a6c267ea2235004dcbcc21b6f3aa7eead1b72c873b18c885a3712728
            env:
              TZ: *timezone
              PGID: 140
              PUID: 1000
            envFrom:
            - secretRef:
                name: posterizarr-secret
            resources:
              requests:
                cpu: 100m
                memory: 4096M
              limits:
                memory: 8192M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 140
        fsGroup: 150
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      assets:
        existingClaim: plex-posters
        globalMounts:
        - path: /assets
      config-file:
        type: configMap
        name: posterizarr-configmap
        globalMounts:
        - path: /config/config.json
          subPath: config.json
      logs:
        type: emptyDir
        globalMounts:
        - path: /config/Logs
