# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app posterizarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      posterizarr:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "0 */1 * * *"
          timeZone: &timezone ${TIME_ZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/fscorrupt/docker-posterizarr
              tag: latest@sha256:a9c56d7fe659721f1efa2de904cb648061b0e147f55ee4435cb9ca06e2bd84a
            command:
              - /bin/sh
              - -c
            args:
              - |
                s6-setuidgid abc pwsh /config/Posterizarr.ps1 -Manual
            env:
              TZ: *timezone
              PGID: 140
              PUID: 1000
            envFrom:
            - secretRef:
                name: posterizarr-secret
            resources:
              requests:
                cpu: 100m
                memory: 4096M
              limits:
                memory: 8192M
    persistence:
      config:
        existingClaim: *app
      assets:
        existingClaim: plex-posters
        globalMounts:
        - path: /assets
      config-file:
        type: configMap
        name: posterizarr-configmap
        globalMounts:
        - path: /config/config.json
          subPath: config.json
      logs:
        type: emptyDir
        globalMounts:
        - path: /config/Logs
