# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app posterizarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      posterizarr:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "0 2 * * *"
          timeZone: &timezone ${TIME_ZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/dapperdivers/posterizarr
              tag: v1.9.34@sha256:63d104caf157c13a7bf54d55891371cd20290b2e638f0b2dbafec65fe8926aef
            env:
              TZ: *timezone
            command:
              - "sh"
              - "-c"
            args:
              - "tail -f /dev/null"
            envFrom:
            - secretRef:
                name: posterizarr-secret
            resources:
              requests:
                cpu: 100m
                memory: 4096M
              limits:
                memory: 8192M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 140
        fsGroup: 150
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/config
      config-file:
        type: configMap
        defaultMode: 660
        name: posterizarr-configmap
        globalMounts:
        - path: /app/config/config.json
          subPath: config.json
      assets:
        existingClaim: plex-posters
        globalMounts:
        - path: /assets
