---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vaultwarden
  namespace: flux-system
spec:
  targetNamespace: security
  dependsOn:
    - name: volsync
    - name: cloudnative-pg
    - name: external-secrets-stores
  path: ./kubernetes/apps/security/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
