---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./homepage/ks.yaml
  #- ./actual/ks.yaml
  #- ./atuin/ks.yaml
  #- ./changedetection/ks.yaml
  #- ./lubelog/ks.yaml
  #- ./paperless/ks.yaml
  #- ./redlib/ks.yaml
