---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    volsync.backube/privileged-movers: "true"
    goldilocks.fairwinds.com/enabled: "true"
    kustomize.toolkit.fluxcd.io/prune: disabled
