---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chelonian-turtle-track
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/chelonian/turtle-track/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dapper-cluster
  wait: true
  dependsOn:
    - name: chelonian-namespace
    - name: chelonian-ghcr-pull-secret
