---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: descheduler
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    kind: Deployment
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    deschedulerPolicy:
      profiles:
        - name: Default
          pluginConfig:
            - name: DefaultEvictor
              args:
                podProtections:
                  defaultDisabled:
                    - FailedBarePods
                    - PodsWithLocalStorage
                    - SystemCriticalPods
            - name: LowNodeUtilization
              args:
                thresholds:
                  cpu: 20
                  memory: 20
                  pods: 20
                targetThresholds:
                  cpu: 50
                  memory: 50
                  pods: 50
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsViolatingTopologySpreadConstraint
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
            deschedule:
              enabled:
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingTopologySpreadConstraint
    service:
      enabled: true
    serviceMonitor:
      enabled: true
