# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ChelonianLabs RoundTable
  - roundtable-chelonian.yaml
  # Chains
  - chelonian-repo-init.yaml
