---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - chelonian-secret.yaml
  - roundtable.yaml
  - pellinore.yaml
  - lamorak.yaml
  - bors.yaml
  - tor.yaml
  - ector.yaml
