# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QTncP8FHB6n69qLJ5dVrWqIzeUMteTku7NxItZYBS1bOk054SxLwHw==,iv:7Bxod53GVnByRr0dTf2PaxJk1GXOiUO+AtzNloK5JL0=,tag:N+NdWEpDtHSLkp+Th7zMdg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMzlOVFljNER1c1IvT2Yx
        ZkdQVmlLOU9zcm9Gd2o4Y2JjVjNYU1h0WUdzCklzLzBrUXlJM01CcFFTYk83NjZz
        WU1RRGNjMElDV0tpM2lHWDM2cGEwMk0KLS0tIGk4VndaZGdRcEpXZFNtV2RUMmZU
        RmVHSEh6YzVQQWlUL1BkajhUL2RMTGsKBCPg+yL4RuMRMBc1SFMni+n4cB3dzLqQ
        2+5LVHJ6rOs9suLzgvjmPbdBBzLBOupe3z256T8peHqq0phh8t9ISw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-03T20:52:50Z"
  mac: ENC[AES256_GCM,data:qmwSANWt97L9i1daeTqzMrv+rzNUcrKKSK19uqO+HDZubaBH3llTZM2yZ9XcBBQBf4wi90eg5SfFU4Zss+uYuP9bstSHL5ZNCTrY/WN3MGKuAprg+l/deHZ5LWJkZUc6yCt9BuZn7VOhsFBYMAhgcr2Qh4V03Y+jNjfNq0RL8mc=,iv:VGk3BMxcOsxGXTqmcF4ttaYkeU/GA5vQkT/kODD0dww=,tag:fLaifWr6ASnMmiz1a0tNjg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
