---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: used-nfs
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: openmediavault-used.manor
  share: /Used/k8s
  subdir: "{{ .Release.name }}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-pvs
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/k8s
  subdir: "{{ .Release.name }}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-data
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/data
  subdir: "{{ .Release.name }}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-backups
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/backups
  subdir: "{{ .Release.name }}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime
  - nodiratime
