---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-admin-secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: GRAFANA_ADMIN_USERNAME
    - secretKey: admin-password
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
