---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt-garage
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/volsync
  dependsOn:
    - name: emqx-cluster
      namespace: database
    - name: volsync
      namespace: volsync-system
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/home-automation/zigbee2mqtt-garage/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: zigbee2mqtt-garage-config
      VOLSYNC_CAPACITY: 5Gi
