# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-secret
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ARGON2_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^VAULTWARDEN_ARGON2_TOKEN$

