---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: posterizarr-watcher
    files:
      - posterizarr.py=./scripts/posterizarr.py
generatorOptions:
  disableNameSuffixHash: true

