---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-off-deck
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: plex
      namespace: media
  values:
    controllers:
      plex-off-deck:
        type: cronjob
        cronjob:
          schedule: "@daily"
          timeZone: &timeZone ${TIME_ZONE}
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/jbops
              tag: rolling@sha256:f3f38aa8ea7e7bedbc9f4929b90e0ba6f08b38c74da5253dfae2707c340b0fe4
            env:
              TZ: *timeZone
              JBOPS__SCRIPT_PATH: utility/off_deck.py
            args: ["--markWatched", "--playlists", "Toons", "SleepMix"]
    persistence:
      secret-file:
        type: secret
        name: plex-off-deck-secret
        globalMounts:
          - path: /config/config.ini
            subPath: config.ini
            readOnly: true
