---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./alert.yaml
  - ./provider.yaml
  # Flux-Kustomizations
  - ./external-secrets/ks.yaml
