---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: imapsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: imapsync-credentials
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # Source provider credentials
        GMAIL_ADDRESS: "{{ .STALWART_GMAIL_ADDRESS }}"
        gmail-password: "{{ .STALWART_GMAIL_IMAP_PASSWORD }}"
        MIGADU_ADDRESS: "{{ .STALWART_MIGADU_ADDRESS }}"
        migadu-password: "{{ .STALWART_MIGADU_IMAP_PASSWORD }}"
        OUTLOOK_ADDRESS: "{{ .STALWART_OUTLOOK_ADDRESS }}"
        outlook-password: "{{ .STALWART_OUTLOOK_IMAP_PASSWORD }}"
        # Stalwart destination credentials
        STALWART_USER: "{{ .STALWART_PRIMARY_USER }}"
        stalwart-password: "{{ .STALWART_PRIMARY_PASSWORD }}"
  dataFrom:
    - find:
        name:
          regexp: ^STALWART.*
