apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:eFMrQy3CD+xls79euGX/y677gvIdZSAvEUdMDDESX0tZf14c,iv:2+5efsviGCFry/w3VMC4FnSzIlefB86gEy3QW5s1f0I=,tag:40l8H+cd6H+HfULC5q+W8w==,type:str]
    credentials.json: ENC[AES256_GCM,data:rICOdG25NyyxgZs9k1t8cLrygULmQJuoWVxN3wMZHfH8H2gpvDkptDJ+6vfof4hnOHVk8azIDQNHc8hNemVGjzRVxKHLdGX5G3KablTcik5TtvZT54f20thln+YEPcce3cW2JFs6J2eUt4G8bBxE7NAvTmOJSvTBVWM4qRRARiNsOS3SDU/EYB7SIJSLZidxSD9kYJweHMLHTvZj5uHyXb23tsREktzGkYMk2+Ry2g==,iv:2FD4rSsUYMuF0HCDJPIJrRruZwpqMncMK+YGGOwWYCY=,tag:4JHwa1l4f+VgiiCTFtaF+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK3BNRWRRbitIcmFxUXJv
            K1FMZGJpUWhLdkhoZy9meVREVmJlaXpkaURvCndvUHBrRW5lRGFlNkN2anp6cTBp
            REVZT20rWEVHMG9XNkFDWnEwQzlEMVUKLS0tIElmMHQ1M1RYR3JvWVdrelhiUkZI
            RkFQVUhxUU8yUncweFFTalI5aFFFVWMK6mzV1fLp2wKjLLdoaesrK0VTkqoQZJcs
            c3gJcb1DaowJN/Mb5GvnPuWzQGyRk/MfFVCMWxnVvf5nxlLcOTKOsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T03:05:26Z"
    mac: ENC[AES256_GCM,data:W0BwKWeFerC6k0rBvryXKo0l/b2NjKuUjfhxz2azDcZ1UyKTcUxcedSLESXhWfxsBLV3F5DxEcemXaSRtEa+bonWAiZCTd5cFJu5SJogeUBTynH3KmOt7SN1lCj9IrREwu09pLDKj68X0F3m3B9gqhoSnhJSYatm3A79WFvbuWU=,iv:eCU0IoOdUBOb+Htey4B62rumQVNfFELtaFRLZQVkjV0=,tag:HIfQf12PP/qIhKNeAJLMqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
