apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9LtgTrtAutwJgEG+L1MoLuRUtZ/j3kIYfTzUOzgi2GTPdp5X,iv:T0M2vGaAbiEmQV31EtWa5CcHMcYBYdt3AFWCVn+MWj0=,tag:kYBORQ+aLTJuxA2sBToybg==,type:str]
    credentials.json: ENC[AES256_GCM,data:27bnQeIP7JqnaiqPIAk856noc1fMny3BwN/vlzg5QsgOFlglT1uUW4FanCb44pV6cMF5+2O21LZuGov/wJJ5i12oeskM+2L9w+6maXv9vW5Oy8uz+97oHdduUvBgIyUawWRx4zZvHIPK4Uvv8r44Dln41/23C/eqG+O1o4Z3Zw+0+OzJA7fEsPkB3Ujre3+H7P8qS16ESepWLC8jkrBBoGPSDXzNZPGgIndsXD4zcA==,iv:OwUwnEouO0mEISaejp0uD0tpvLed1wqmncPZWZb1DXE=,tag:w9/pYcPXob81XTKx4KQ1WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRUo3QTdrT2d4bGp2ZDdF
            VnhzdVFWUlV3RVg2elZVYUZaZXYzYU1DY3pzCmtia091MldpeXFINDZzQUhIRWlU
            OS8rd0s5Y2N6RVNJTGN0UWp4dmdjdGMKLS0tIGRISXY2MkQvaEZjcWUrbmVSeXVv
            NnhWck1sZVcyZ2hITC82cDZ0RWdBcXMKDsxIl7qMXzvRbQPKhO2du8BXlXwCn6w+
            IRy6bVKJvKarc4pMNrah7tdSuz3djoaeVBL5F/QTYkkoaf/7by8Cmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T22:43:12Z"
    mac: ENC[AES256_GCM,data:A9scuxJt+xQDVxGb0h8lSTuJDW7PgvGlrVLqj9TbQGRBvrxaf0IkgrFnKODPbxnBmGAOE275CkrxEXo+fTYd+dlg6rFdYdM1oeZDQ5memjYRUQopSsygthQ7IXDUhp0ivjnt82/YnHj/gy27DJakNzRC2QjekdpdP9mhkwS6dyA=,iv:0VWXYS8j1MX3vCBN4tz+4pf5ka84KWKVAOK1ZhW55oM=,tag:l4MZc3dm7C3x8LcRgv/00g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
