apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:caV6RgQLR4aCWaTgPe4oIa76wgct4+qfb4k8LRCZI1+OtX5r,iv:EDPEQP0LxD6Z3BJHiewgc1fRtOlSJPQzurzFemq/mSM=,tag:n/6cfNkuXjgKsr9R2Sgehg==,type:str]
    credentials.json: ENC[AES256_GCM,data:/3S1s2kWsTyYml+vnv4+Xzz9CJAiGWMpkpWkee89G5LiCcW2J+o8Kht0CZinb7vXjJKapOxYuu5XMoea2YyeXUGQYXQiN14RsfXimT/yFGV1Km1FoNt2XYxRZ519plohpu/eFIlaTSwl9TmuAvtFJ7sUY4cII4t91lrguoF9wjAeokHS1/853AWvxzZ5aJJB8goKYhWwtddTvB/OmaYTYGgyvRZwHpH+cBtpRHQMIw==,iv:aafm7Jw5J4WQx7dAE4cm0FVP3mRt2LpA3GDFdCkIe60=,tag:TXMlFMxphujOEoEXtxR4KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRDF3N2swYmVYZUt0UllK
            SGduajUvZHNuVzN3L05EV0RGNWV4WXBkQ3lzCjRhT29XZHE1bmt3SWhMN0NJb21x
            Y3F2ckdvN2xvS0trNmRHQkI3VjB0KzAKLS0tIHdKbjJyb0p1SHQvQWhKM2NaZ2xy
            NlcwSmFPb1NWZ3hJS3ZoSUFxOGs5Qm8KmnH60B63H7QD7psbr17GNzdrTzSiCRTG
            pYttb1qYpJbTCQnxN63VPQAyi9nRzBxbqAplSjtRM6cogyur30Q92Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T04:33:29Z"
    mac: ENC[AES256_GCM,data:0uzkY+CCkwp6iFDvjEPD04Vgz8XcoWk6CSy6EdDS4hSphmMTsWpsxXyV0dm7HqQcdaKXyb1C1aBVX0500LvIrNo6PhQmNFNgzVveVq0d2Bd2e4mfHhkMiC2WiRQ4ALb0yGdyiVQEXbKC8c0/FPo0D77ckVh58NdWqXRGzFTtrig=,iv:Jep6o/imW0x7Ikgk9OB4Djbkej1Fu60Vple4WHxSJmw=,tag:yNu92IW9ydQJBFNgjAdryw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
