---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease-maxhistory.yaml
  - ./httproute-authentik-forward-auth.yaml
  # - ./nfs-health-checks.yaml
  - ./postgres-init
  - ./pod-security
