---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: recyclarr-secret
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: SONARR_API_KEY
    - secretKey: sonarr_uhd_api_key
      remoteRef:
        key: SONARR_UHD_API_KEY
    - secretKey: radarr_api_key
      remoteRef:
        key: RADARR_API_KEY
    - secretKey: radarr_uhd_api_key
      remoteRef:
        key: RADARR_UHD_API_KEY
