---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: recyclarr-secret

  dataFrom:
    - find:
        path: 4K_RADARR_API_KEY
    - find:
        path : 4K_SONARR_API_KEY
    - find:
        path: SONARR_API_KEY
    - find:
        path: RADARR_API_KEY
