---
apiVersion: batch/v1
kind: Job
metadata:
  name: finance-postgres-init
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:17.6@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
          env:
            - name: INIT_POSTGRES_HOST
              value: postgres-rw.database.svc.cluster.local
            - name: INIT_POSTGRES_PORT
              value: "5432"
            - name: INIT_POSTGRES_SUPER_USER
              valueFrom:
                secretKeyRef:
                  name: finance-postgres-superuser
                  key: POSTGRES_SUPER_USER
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: finance-postgres-superuser
                  key: POSTGRES_SUPER_PASS
            - name: INIT_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: finance-app-secret
                  key: CHELONIAN_DB_USER
            - name: INIT_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: finance-app-secret
                  key: CHELONIAN_DB_PASS
            - name: INIT_POSTGRES_DBNAME
              value: "finance_main finance_auth finance_user_org finance_file finance_transaction finance_categorization finance_ai"
