---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-uhd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: radarr-uhd-secret
  data:
    - secretKey: api_key
      remoteRef:
        key: RADARR_UHD_API_KEY
