---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-uhd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: 4k-radarr-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        RADARR__AUTH__APIKEY: "{{ .4k_radarr_api_key }}"
        PUSHOVER_API_TOKEN: "{{ .PUSHOVER_API_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"

  data:
    - secretKey: 4k_radarr_api_key
      remoteRef:
        key: 4K_RADARR_API_KEY
