---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chelonianlabs-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-chelonian
  target:
    name: chelonianlabs-runner-secret
    template:
      engineVersion: v2
      data:
        CHELONIAN_RUNNER_APP_ID: |-
          {{ .CHELONIAN_RUNNER_APP_ID }}
        CHELONIAN_RUNNER_GITHUB_INSTALLATION_ID: |-
          {{ .CHELONIAN_RUNNER_GITHUB_INSTALLATION_ID }}
        CHELONIAN_RUNNER_GITHUB_PRIVATE_KEY: |-
          {{ .CHELONIAN_RUNNER_GITHUB_PRIVATE_KEY }}
  dataFrom:
    - find:
        path: /github
        name:
          regexp: "^CHELONIAN_RUNNER_"
