---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: recyclarr-secret

  dataFrom:
    - find:
        name:
          regexp: ^RADARR_UHD_API_KEY$
    - find:
        name:
          regexp: ^SONARR_UHD_API_KEY$
    - find:
        name:
          regexp: ^SONARR_API_KEY$
    - find:
        name:
          regexp: ^RADARR_API_KEY$
