---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudnative-minio-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        aws-access-key-id: ${.MINIO_ROOT_USER}
        aws-secret-access-key: ${.MINIO_ROOT_PASSWORD}

  dataFrom:
    - find:
        path: MINIO_ROOT_USER
    - find:
        path: MINIO_ROOT_PASSWORD

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: ${.POSTGRES_SUPER_USER}
        password: ${.POSTGRES_SUPER_PASS}
  dataFrom:
    - find:
        path: POSTGRES_SUPER_USER
    - find:
        path: POSTGRES_SUPER_PASS


