---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chelonian
  namespace: roundtable
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-chelonian
  target:
    name: chelonian-secret
    template:
      engineVersion: v2
      data:
        GH_TOKEN: "{{ .AGENT_CHELONIANLABS_GITHUB_TOKEN }}"
        GITHUB_TOKEN: "{{ .AGENT_CHELONIANLABS_GITHUB_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^AGENT_CHELONIANLABS.*
