---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - molt-rbac.yaml
  - roundtable-secret.yaml
  - vault-pv.yaml
  - vault-pvc.yaml
  - shared-workspace-pvc.yaml
