---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-chelonian
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-chelonian
  target:
    name: ghcr-chelonian
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"auth":"{{ printf "dapperdivers:%s" .AGENT_CHELONIANLABS_GITHUB_TOKEN | b64enc }}","username":"dapperdivers","password":"{{ .AGENT_CHELONIANLABS_GITHUB_TOKEN }}"}}}
  dataFrom:
    - find:
        name:
          regexp: ^AGENT_CHELONIANLABS_GITHUB_TOKEN$
