---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-single-replica
