---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nut-upsd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      nut:
        containers:
          app:
            image:
              repository: docker.io/instantlinux/nut-upsd
              tag: 2.8.2-r0
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
            env:
              TZ: ${TIME_ZONE}
              DRIVER: "usbhid-ups"
              DESCRIPTION: "Main Cluster UPS"
            envFrom:
              - secretRef:
                  name: nut-upsd-secret
        pod:
          nodeSelector:
            ups.feature.node.kubernetes.io/apc: "true"
    service:
      app:
        controller: nut
        ports:
          http:
            port: 3493
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        className: internal
        hosts:
          - host: &host ups.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN/./-}-tls
