apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
            - "${SECRET_DOMAIN_MEDIA}"
            - "${SECRET_DOMAIN_PERSONAL}"
            - "${SECRET_DOMAIN_DIVING}"
            - "${SECRET_DOMAIN_WIFE}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
            - "${SECRET_DOMAIN_MEDIA}"
            - "${SECRET_DOMAIN_PERSONAL}"
            - "${SECRET_DOMAIN_DIVING}"
            - "${SECRET_DOMAIN_WIFE}"

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cert-production
spec:
  acme: # Using staging for a bit to fix the cluster
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
            - "${SECRET_DOMAIN_MEDIA}"
            - "${SECRET_DOMAIN_PERSONAL}"
            - "${SECRET_DOMAIN_DIVING}"
            - "${SECRET_DOMAIN_WIFE}"
