apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:RG+/mVZtBkXUwi2VkhmrwmIHCJvvw5ZslqIgx/f5ehFyxMtC1cjK2A==,iv:SITZa7JpwEi5OF3aJESF6Ov9ISmWuAyy2gEvqVkgbdk=,tag:ttupBAcoDOb7IL2BrYXmxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocmx1L0U3NThUMUhxNG4z
            RmE3NzNxeTQ2NW41KzdXSUNSOTh5bm8vcjI4CkhmbzkwVXNybjVDY240STd5QkJI
            MDJYNXR2NG1KWGFhSFZPellmOERDaTQKLS0tIDlwdVR1T3FDR2dENExycjZ4QVFj
            UjdWYUN3aUUvWlFIQWt0ZjZCMkExR2MKuXC+/SYMrAGmjJkJtS+cAcWZz/HTIjvU
            0alA16c3PRkP49bpTHiwOSwlZjAeTXlbYmCxnTwxRRzGc8KuaufDzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T03:59:20Z"
    mac: ENC[AES256_GCM,data:ZxObR1zjgjYen/ivrgeRGJdF/TvCkrStN3106WHdOluNOmu3IbCQMdZTQxaIXsZFyD1KXvthw+GGv8UTsNY+KB1R7NhzrN2kTgoByZiVOTX/J5uVCWFYKT0+pS7WmsUNjNAWlGJtjU6JDslIO0ImxegXO5OOS/ev/ITdzIR6vOA=,iv:jydxNYD+ghJ4S1DYcEyfKdLxWia82E9qfk0JHPoOyrs=,tag:W/NJojG/LOjaVzSlacpsAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
