apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:wEbMTwE1lj1ph9cGmh2/vkyxQ0uB8fXZgH4JieDdZJrIwZD9xnQ3ew==,iv:BG8XBC85te48swbJj4963tpjC8F/IjX4fhfSJaWUr08=,tag:yXb9RprzPZPXuXFLUCp9YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdUJndkY3TEw0THZnY05L
            ODhObk93TUlwWWxOVVNjSGNFQUV4L2dYQndFCnhBUUhqMnFwSnhURzhNcWowaVo0
            dUNLRkFyUVYyNEM2UUpqUU9wY2t2SkkKLS0tIElJdGsxYU03L0g3M2Q4SFVsUTJr
            K1UrRStQaFVtenRyOFpIT2F6UVhBTzgKqJNmtbzz+/3u7A7Wy2aF2tj9LlCwA0k5
            YbXLEZt/TcG4nxOVRryP9KyRBH8/j2oA9yhJwdzOFg20fcZL14+8sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T04:33:29Z"
    mac: ENC[AES256_GCM,data:uNddc2Zpw57yKODcLbydp/wqEXTWj+R624FV4/sBa5uXUiWaE5ePiG5gJ+QFHwA8vpXkHcgLyazlVOPVOb9FrRxyO/+bz5pFZXyZXrKD1XDiWKUV/1sRnMJ9h9RKu/VHwKm6izgXoJadWnrwq3MhAEfFwKGX6xycsAxviG4PX2E=,iv:d/dUBFJOc+BAWnH8dw5nAG+TTh714HlsxvpEIirdBBY=,tag:mwLkaN8L9UpNT3nJhTonsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
