# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZvVXJC2Z4iuL13cAAaVnm6V2jANmrf9pidDdZdV0wnwKTxC3v8y/nw==,iv:6/NzmOVPf7H+HqFWT7VuUr49758uHttGIJQJxNhEjDw=,tag:UkoeQcKig+oDREvADLbB4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMHhyNG9Rakg0ZHBHaXg5
            d2M4T0NBWldVZERiNVlMVDBqN29EZlZ5bDFRCkxxTUNrcnZUSXVady9RTWNlcGdH
            TkpZRHd0RUxxeE1nSk5jNmNTTFJqVkkKLS0tIGN5UUg4SXIzQjk1YmhjbDAxeHBk
            Q0NpWktEemp2RnlhdXQ2WnlrZ09pRTAKNAL6MUiCFvyreEdYjhrDZlIWq4+TC5qx
            EDbn4YqufSE57A4zDrveZP8ZSZy4jiYzc0QoJSyA4IOCXuVCDKlHQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-06T20:42:47Z"
    mac: ENC[AES256_GCM,data:BkkaK7pxjsGYQ6HSQjK7beCU7TKCi44Ml1Qfpb8Wb6wBAx5EkBzq3V++vm9mwwWTCJwmKxuH7nDDEkjd+zpQtmeIIaHmKtVheiMBqdHRARGoTfbGf+2STJztMJ/GMA8BQcKMUJPYwauXYHF03z2VeVqrDlyHVTfxjZhZVEjAGII=,iv:HFeW26xtHJBamnlUyuWIsgKx3C/bK25DM+cj6OzbtZM=,tag:RIcYXBLnNRWfq+tm7yH/fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
