apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cBOE14xPi4MLpEqs1Kpim+pfC9PG62vfyYbF7t9msO2QHHEx8b7RQA==,iv:LfThaBZ4Zbj3etJWzdUo7oHL2WwRzHatoUGLKUur7r0=,tag:Z2o+UMtBEjomqE6D1rr4dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SDFNQWdVY2liUmtTdnNN
            dGl0Z2swbWVtQ0ZnaTVvVzBsdmkzVGY2bXdjCnRaT1pSeHVVeFFaYXN0YVllZi9i
            c1pNOGxmSnp2V1lvMlByVHN0NDRrbDAKLS0tIEJieC90RXptd0kxa1ZCanB5OVMx
            bFRGOCs1ajVmTW5JWGJ5QkpwRGhpTDAKF59UDsotaGXkJ3t9peNnM5A+iXVmeZp2
            lTQiHlDHEpMkF6988ZzCi7KQ5NJEF7aImffFFZYtHYPSltXjjg3Jlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T01:54:52Z"
    mac: ENC[AES256_GCM,data:c1zVoOJWAmEgF3upCOeTVFVJaCLZgJoMjENZG1wEGXAJIITmfK1wztayEBiSWRGX1Mo8+RvVsv+u+e9Qs8tfldk5LGf8bS10jFqXeKaMHr1gys5pkWIX5suy4Qut15V4MWGSzC334uQM8R/rUt1Y3Z962XKGYLYbmq21g7DrWKM=,iv:1XAZehmLts7VJl2BST3A2g1DPLWY5kvsrc3dvm5hAHc=,tag:aQbb3mhOKYVhxKFxT5jzng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
