---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: zigbee2mqtt-secret
    template:
      engineVersion: v2
      data:
        # TODO: Get this figured out with existing network
        #ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID }}"
        #ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID }}"
        #ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY }}"
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .EMQX_MQTT_USERNAME }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .EMQX_MQTT_PASSWORD }}"
  dataFrom:
    - find:
        path: EMQX_MQTT_USERNAME
    - find:
        path: EMQX_MQTT_PASSWORD
   # - find:
   #     path: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
   # - find:
   #     path: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
   # - find:
   #     path: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
