---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: used-nfs
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: openmediavault-used.manor
  share: /export/Used
  subDir: /k8s
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-pvs
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/k8s
  subDir: /
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-cache
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/k8s
  subDir: "cache/${pvc.metadata.namespace}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-data
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/data
  subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - nconnect=8
  - hard
  - noatime
  - nodiratime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-backed-backups
  labels:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
provisioner: nfs.csi.k8s.io
parameters:
  server: circe.manor
  share: /ssd/backups
  subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
  - nconnect=8
  - hard
  - noatime
  - nodiratime
