apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./home-assistant/ks.yaml
  - ./node-red/ks.yaml
  - ./esphome/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zigbee2mqtt-garage/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: home-automation
    target:
      kind: Namespace
