apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
components:
  - ../../flux/components/common
resources:
  - ./home-assistant/ks.yaml
  - ./node-red/ks.yaml
  - ./esphome/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zigbee2mqtt-garage/ks.yaml
