---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-uhd/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-uhd/ks.yaml
  - ./overseer/ks.yaml
  - ./plex/ks.yaml
  - ./wizarr/ks.yaml

