---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chelonian
  namespace: flux-system
spec:
  targetNamespace: roundtable
  commonMetadata:
    labels:
      app.kubernetes.io/name: chelonian
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/apps/roundtable/chelonian/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: roundtable-operator
    - name: roundtable-infrastructure
