---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: actual-secret
    template:
      engineVersion: v2
      data:
        ACTUAL_OPENID_CLIENT_ID: "{{ .ACTUAL_OPENID_CLIENT_ID }}"
        ACTUAL_OPENID_CLIENT_SECRET: "{{ .ACTUAL_OPENID_CLIENT_SECRET }}"
  dataFrom:
    - find:
        name:
          regexp: ^ACTUAL_OPENID.*
