---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://ghcr.io/dragonflydb/dragonfly/helm
