---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./backube.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./dragonfly.yaml
  - ./dcgm-exporter.yaml
  - ./emqx.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./infisical.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./k8s-gateway.yaml
  - ./kyverno.yaml
  - ./loft-sh.yaml
  - ./node-feature-discovery.yaml
  - ./nvidia.yaml
  - ./ollama.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook.yaml
  - ./spegel.yaml
  - ./vllm.yaml
  - ./nats.yaml
  - ./opencti.yaml
  - ./wazuh.yaml
  - ./roundtable.yaml
