---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &chart csi-driver-nfs
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: *chart
      version: v4.10.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: openebs-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    feature:
      enableFSGroupPolicy: true

    controller:
      replicas: 1
      strategyType: Recreate
      resources:
        csiProvisioner:
          limits:
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 30M
        csiSnapshotter:
          limits:
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 30M
        livenessProbe:
          limits:
            memory: 500M
          requests:
            cpu: 10m
            memory: 30M
        nfs:
          limits:
            memory: 8000M
          requests:
            cpu: 500m
            memory: 160M
            defaultPodOptions:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 150
          fsGroup: 140
          fsGroupChangePolicy: OnRootMismatch
          seccompProfile: { type: RuntimeDefault }
