---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../flux/components/alerts
  - ../../flux/components/namespace
  - ../../flux/components/sops
  - ../../flux/components/substitutions
resources:
  - ./actual/ks.yaml
  - ./unifi/ks.yaml
  - ./open-webui/ks.yaml
  - ./n8n/ks.yaml
  - ./ollama/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./searxng/ks.yaml
  - ./obsidian-couchdb/ks.yaml


