---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agravain
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: agravain-secret
    template:
      engineVersion: v2
      data:
        SHODAN_API_KEY: "{{ .SHODAN_API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ^SHODAN.*
