---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kometa-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR_UHD_API_KEY: "{{ .RADARR_UHD_API_KEY }}"
        TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        OMDB_API_KEY: "{{ .OMDB_API_KEY }}"
        MDBLIST_API_KEY: "{{ .MDBLIST_API_KEY }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        SONARR_UHD_API_KEY: "{{ .SONARR_UHD_API_KEY }}"
        TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"

  dataFrom:
    - find:
        path : TMDB_API_KEY
    - find:
        path : OMDB_API_KEY
    - find:
        path : MDBLIST_API_KEY
    - find:
        path : PLEX_TOKEN
    - find:
        path: RADARR_API_KEY
    - find:
        path: RADARR_UHD_API_KEY
    - find:
        path: SONARR_API_KEY
    - find:
        path: SONARR_UHD_API_KEY
    - find:
        path : TAUTULLI_API_KEY

