---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name:  &app kometa

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: plex
      namespace: media
    - name: volsync
      namespace: storage

  values:
    controllers:
      kometa:
        type: &type cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob: &cronjob
          schedule: "30 4 * * *"
          timeZone: &timeZone ${TIME_ZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app: &container_app
            image:
              repository: kometateam/kometa
              tag: develop@sha256:cbeec2bf8007dd7183bc86d1b179d313e83eed5da69ecfd04b571716ef4c20c5
            command:
              - /bin/sh
              - -c
            args:
              - |
                python3 kometa.py --run --read-only-config --run-libraries "4k-Movies";
            #args:
            #  - |
            #    python3 kometa.py --run --read-only-config --run-libraries "4k-Movies";
            #    python3 kometa.py --run --read-only-config --run-libraries "Movies";
            #    python3 kometa.py --run --read-only-config --run-libraries "4k-TV Shows";
            #    python3 kometa.py --run --read-only-config --run-libraries "TV Shows";
            env:
              TZ: *timeZone
            envFrom:
              - secretRef:
                  name: kometa-secret
            resources:
              requests:
                cpu: 100m
                memory: 4096M
              limits:
                cpu: 2000m
                memory: 8192M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/bash", "-c", "mkdir -p /config/assets/{anime,awards,decades,genres,holidays,networks,suggestions,posters}"]
      standard-movies:
        type: *type
        cronjob:
          <<: *cronjob
          schedule: "0 12,18 * * *"
        containers:
          app:
            <<: *container_app
            args:
              - |
                python3 kometa.py --run --read-only-config --run-libraries "Movies"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 140
        fsGroup: 150
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      config-file:
        type: configMap
        name: kometa-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      assets:
        existingClaim: plex-posters
        globalMounts:
        - path: /config/assets
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
