---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name:  &app kometa

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: plex
      namespace: media
  values:
    controllers:
      kometa:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: "@daily"
          timeZone: &timeZone ${TIME_ZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: kometateam/kometa
              tag: v2.1.0@sha256:af441b1eeaa3be6a55820f16102d950d12fa52f3bb791b835a6a768385cd3a30
            command:
              - /bin/sh
              - -c
            args:
              - |
                python3 kometa.py --run --read-only-config --run-libraries "4k-Movies";
            #args:
            #  - |
            #    python3 kometa.py --run --read-only-config --run-libraries "4k-Movies";
            #    python3 kometa.py --run --read-only-config --run-libraries "Movies";
            #    python3 kometa.py --run --read-only-config --run-libraries "4k-TV Shows";
            #    python3 kometa.py --run --read-only-config --run-libraries "TV Shows";
            env:
              TZ: *timeZone
            envFrom:
              - secretRef:
                  name: kometa-secret
            resources:
              requests:
                cpu: 2000m
                memory: 4096M
              limits:
                cpu: 5000m
                memory: 8192M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 140
        fsGroup: 150
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      config-file:
        type: configMap
        name: kometa-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
