---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    ---
    - Links:
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com/feed/subscriptions
        - Spotify:
            - icon: spotify.png
              href: http://open.spotify.com
    - Git:
        - GitHub:
            - icon: github.png
              href: https://github.com
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster
  services.yaml: |
    ---
    - Media:
        - HomeAssistant:
            href: https://home.${SECRET_DOMAIN}
            icon: home-assistant.png
            description: Home Assistant
            widget:
              type: homeassistant
              url: http://home-assistant.home.svc.cluster.local
              key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
        - Plex:
            href: https://plex.${SECRET_DOMAIN}
            siteMonitor: https://plex.${SECRET_DOMAIN}
            icon: plex.png
            description: Movies & TV
            widget:
              type: tautulli
              url: http://tautulli.media.svc.cluster.local
              key: "{{HOMEPAGE_VAR_TAUTULLI_TOKEN}}"
              enableUser: true
              showEpisodeNumber: true
              expandOneStreamToTwoRows: true
        - Overseer:
            icon: overseerr.png
            href: https://www.${SECRET_DOMAIN_MEDIA}
            description: Media Requests
            widget:
              type: overseer
              url: http://overseer.default.svc.cluster.local:3579
              key: {{HOMEPAGE_VAR_OVERSEER_KEY}}
        - Immich:
            icon: immich.png
            href: https://photos.${SECRET_DOMAIN_MEDIA}
            description: Photos and Videos Backup
            widget:
              type: immich
              url: http://immich-server.default.svc.cluster.local:2283
              key: {{HOMEPAGE_VAR_IMMICH_KEY}}
              version: 2
        - qBittorrent:
            icon: qbittorrent.png
            href: https://qbit.${SECRET_DOMAIN_MEDIA}
            description: Torrent Management
            widget:
              type: qbittorrent
              url: http://qbittorrent.default.svc.cluster.local:8080
              username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
              password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
        - Radarr:
            icon: radarr.png
            href: https://radarr.${SECRET_DOMAIN_MEDIA}
            description: Movies Management
            widget:
              type: radarr
              url: http://radarr.default.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_RADARR_KEY}}
        - 4kRadarr:
            icon: radarr.png
            href: https://4kradarr.${SECRET_DOMAIN_MEDIA}
            description: Movies Management
            widget:
              type: radarr
              url: http://radarr-uhd.default.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_4K_RADARR_KEY}}
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.${SECRET_DOMAIN_MEDIA}
            description: TV Shows Management
            widget:
              type: sonarr
              url: http://sonarr.default.svc.cluster.local:8989
              key: {{HOMEPAGE_VAR_SONARR_KEY}}
        - 4kSonarr:
            icon: sonarr.png
            href: https://4ksonarr.${SECRET_DOMAIN_MEDIA}
            description: TV Shows Management
            widget:
              type: sonarr
              url: http://sonarr-uhd.default.svc.cluster.local:8989
              key: {{HOMEPAGE_VAR_4K_SONARR_KEY}}
        - Lidarr:
            icon: lidarr.png
            href: https://lidarr.${SECRET_DOMAIN_MEDIA}
            description: Musics Management
            widget:
              type: lidarr
              url: http://lidarr.default.svc.cluster.local:8686
              key: {{HOMEPAGE_VAR_LIDARR_KEY}}
        - Bazarr:
            icon: bazarr.png
            href: https://bazarr.${SECRET_DOMAIN_MEDIA}
            description: Subtitles Management
            widget:
              type: bazarr
              url: http://bazarr.default.svc.cluster.local:6767
              key: {{HOMEPAGE_VAR_BAZARR_KEY}}
        - NzbGet:
            icon: nzbget.png
            href: https://nzbget.${SECRET_DOMAIN_MEDIA}
            description: Usenet Downloader
            widget:
              type: nzbget
              url: http://nzbget.default.svc.cluster.local:6767
              key: {{HOMEPAGE_VAR_NZBGET_KEY}}
    - Network:
        - OpnSense:
            icon: opnsense.png
            href: https://firewall.manor
            description: Router
            widget:
              type: opnsense
              url: https://firewall.manor:8443/
    - Favorites:
        - My GitHub Repo:
            icon: si-github
            href: https://github.com/dapperdivers
            description: My Code Repository
        - Grafana Dashboard:
            icon: si-grafana
            href: https://grafana.${SECRET_DOMAIN}
            description: My Cluster Metrics Visualization
        - k8s-at-home-search:
            icon: si-kubernetes
            href: https://kubesearch.dev/
            description: Search KAH HelmReleases
        - onedr0p home-ops:
            icon: si-github
            href: https://github.com/onedr0p/home-ops
            description: onedr0p HomeOps Repository
        - bjw-s Chart Values:
            icon: si-github
            href: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common#values
            description: app-template Helm Chart Values
  settings.yaml: |
    ---
    title: Home Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    target: _blank
    layout:
      Media:
        style: row
        columns: 4
      Network:
        style: row
      Favorites:
        style: row
        columns: 3
    quicklaunch:
      searchDescription: true
      hideInternetSearch: true
      hideVisitURL: true
  widgets.yaml: |
    ---
    - search:
        provider:
          - google
          - duckduckgo
    - openmeteo:
        label: Home
        latitude: {{HOMEPAGE_VAR_HOME_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_HOME_LONGITUDE}}
        units: metric
        cache: 5
    - openmeteo:
        label: Shop
        latitude: {{HOMEPAGE_VAR_SHOP_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_SHOP_LONGITUDE}}
        units: metric
        cache: 5
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: home-cluster
        nodes:
          show: false
