---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: *name
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ## Infrastructure
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .unifi_user }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .unifi_pass }}"
        HOMEPAGE_VAR_UPTIMEROBOT_KEY: "{{ .uptimerobot_key }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .hass_token }}"

        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .prowlarr_token }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .radarr_token }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .sonarr_token }}"
        HOMEPAGE_VAR_4KRADARR_TOKEN: "{{ .4k_radarr_token }}"
        HOMEPAGE_VAR_4KSONARR_TOKEN: "{{ .4k_sonarr_token }}"

        ## Selfhosted
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .paperless_token }}"

        HOMEPAGE_VAR_HOME_LATITUDE: "{{ .home_latitude }}"
        HOMEPAGE_VAR_HOME_LONGITUDE: "{{ .home_longitude }}"

        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID: "{{ .cloudflare_accountid }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID: "{{ .cloudflare_tunnelid }}"
        HOMEPAGE_VAR_CLOUDFLARE_KEY: "{{ .cloudflare_key }}"

        HOMEPAGE_VAR_TAUTULLI_KEY: "{{ .tautulli_key }}"
        HOMEPAGE_VAR_OVERSEERR_KEY: "{{ .overseerr_key }}"

  data:
    ## Non Cluster
    - secretKey: unifi_user
      remoteRef:
        key: UNIFI_USER
        property: username

    - secretKey: unifi_pass
      remoteRef:
        key: UNIFI_PASSWORD
        property: password

    - secretKey: uptimerobot_key
      remoteRef:
        key: UPTIMEROBOT_API_KEY

    - secretKey: cloudflare_secret
      remoteRef:
        key: TUNNEL_SECRET
    - secretKey: cloudflare_accountid
      remoteRef:
        key: ACCOUNT_TAG
    - secretKey: .cloudflare_tunnelid
      remoteRef:
        key: TUNNEL_ID


    ## In Cluster
    - secretKey: hass_token
      remoteRef:
        key: HOMEASSISTANT_TOKEN

    ## Downloads
    - secretKey: prowlarr_token
      remoteRef:
        key: PROWLARR_TOKEN

    - secretKey: radarr_token
      remoteRef:
        key: RADARR_API_KEY

    - secretKey: sonarr_token
      remoteRef:
        key: SONARR_API_KEY

    - secretKey: 4k_radarr_token
      remoteRef:
        key: RADARR_UHD_API_KEY

    - secretKey: 4k_sonarr_token
      remoteRef:
        key: SONARR_UHD_API_KEY

    - secretKey: paperless_token
      remoteRef:
        key: PAPERLESS_API_TOKEN

    ## Data
    - secretKey: home-latitude
      remoteRef:
        key: HOME_LATITUDE
    - secretKey: home-longitude
      remoteRef:
        key: HOME_LONGITUDE
