---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tensorzero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: tensorzero-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .OPENCLAW_ANTHROPIC_API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ^OPENCLAW_ANTHROPIC_API_KEY$
