---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./blackbox-exporter/ks.yaml
  - ./exporters/dcgm-exporter/ks.yaml
  - ./grafana/ks.yaml
  - ./goldilocks/ks.yaml
  - ./promtail/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./vpa/ks.yaml

components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: observability
    target:
      kind: Namespace
