apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qzrmq0rAQ2zGKbXnp6+Fkw==,iv:QLM+PibizSb1wquY9Heu27PE3vu7KNNlvLUliC7Nglk=,tag:WOZ6S3ttKo7nUPIkXjWPJw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/7IQ6ms6ixICb/Vducs7+p4T1AaiAK9lwA==,iv:Zf3vqtPy28wzoe3pMYQAACMZ2U8Lzqq98mmSp5deFIU=,tag:Tx7Q+fItVDUK8Za2RooGcQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:H0rWmUByCFNwvFR+S1EUJ9+xJfYSZVH4bzREXsNBK2e7jxYv,iv:ufxw8NHOV0CkqsPUldG959RPXzRcsqwBkwZiJFBiUic=,tag:enLSWKoC63kGNmwVeAnM3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j6u0d4jpxu9nf3y77trs9pzde7jxurjjxzvw7p6rvfykf5n4jv6sh3gyd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3b1VtSW9lc21uR293dzl4
            ME5DUFJBUmdQOS9nOUZuMm5YNUUzZlZJdjN3CkpZcTNvU0JPUURRNS95QjBCTXhn
            Q0xveXVaekx2Ukk0VjVBUkxLb0IvY1UKLS0tIGxoNVoxVVdBTDRxRnY5MGt4Vmcx
            OGkvMmM2QzlBYldBUG5aYTVVa2NObHcKbpHT+SLAV+V6ObbuRHkuoetUtfSDra9e
            HOhhQGdqz4gkQLpkPI6KlzzdWjFlw3rBJAawWv5oj9d2LMEhx/a7pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T21:52:51Z"
    mac: ENC[AES256_GCM,data:naDdhz/JqS0gGCzBjwCfPTMA8IJqW3cyN+QHZgb0LPxgUDD+F2J2F4rG7R7ZBUIBf/E89gKmD71ZMWy+ZhhgwgDRXUuWf/GmH8ZbgZbR1pQ3RBuPNy7wwUp3bAxrQgg3BEHAh5U/lHKdH2QWxLVd0eArmW+o1BYwrZ3T2ltbick=,iv:nENhndKCe6/pVnpqd5Tz/10FCMlBQ73O1e8l9PtGfVc=,tag:cuq3BZGBlyTrY6SneVPs8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
