apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jduEAGUwCk0gKx0FR4cR7A==,iv:M2sC28KJOpPyOo5UrCJsq+mTc85vTYe70tL1o8O+Cs4=,tag:h59S/emhky8pxfimCZxIhA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JEwxrUEIpmn3YLGYmkdQBcfrE/10r8mM1w==,iv:1XhWsN84tzE2w9Ks58EgR5Hjf6IcDhmuIKAoXfejPtY=,tag:BBqGOFA82DLI8kxQnxKv3A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AH5xjHdynC48yDcrtWH/bV369+wZBCTE9HBlK75uKmaUPXuo,iv:fOILnvpJ1uZqR10RGH+VB8XdBK63ukKgC24sDtgu6Wk=,tag:S3LK9jRA1CwbzZO4UU5+2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb1FyK1NabWxZdWFJRWQ5
            b1VubFRQeVNqaWI1WU1zeHpGZXlqVHV0c0ZvClRxTHE2Q2ZwOCtOSVlyRkx1R1B1
            eTFUSUZ4YkZFTzdGdXdLMHRXbGpYeVkKLS0tIDVjQkNvdzdiZkZOUHZyOTN0NHlK
            Q1Y5RExDU1U3QXdYS2huZzhiME5VT28KPce0kPCIXKqlehYGRn8RB/TGCmmQbDRQ
            3F4YPWJiptVQm6dFJwZ+hAJl8JwYxyiSdz8Zf7jrBpQC1oZmKilN/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T03:59:20Z"
    mac: ENC[AES256_GCM,data:8cz2NAlvmhEOVmN7718O0cdSNhmbLmzRr0xwPsbnMr7SOJqcj+744B29VSAqkN54C25GFw5p0LCJ0lm6iDTNkAaCWSLH46sgDrz8BTsCkAF2yy70I/kvzMgy8BPT0HWgTnt5Sb2K/ry/Q8ou1UYVMNf/i/J2nf7QxgJguvDuruw=,iv:5OJ5rEO2GEhYqrSyl0vhca6Msl+HTnQkiI2DvhTjWOU=,tag:7Zc8zVJr2K6eI9mL0/hAXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
