apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mXQLc8hC0Xcbcg00Cyt4pg==,iv:p06avdS9aMAQtBuOTaJ4Ej+35XBKqiXUobMDfKaHyVk=,tag:o6afmZ3eSHr7RyyhqiQ+JQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IJCn3uH7Ywd1yWCBMWLnBZ/RAgT0xy2fNw==,iv:F0e/l7oulpo7bp2RyeoLHBtjbv8fbeGG4vUBMP0a3ro=,tag:mJPNPIxb9DdTijFsaJt+fw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xvhiublQPDps5k1I7swtQziCfz4InrHidor+dguYawOuV+ys,iv:o6rKuAspA5m/vh/lKMxzcTA7ojxlyOzZnCrpD+iVnJU=,tag:JD8kcexf0gMm02YDchI05w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2hwbjJ5YnJna2ZIei9K
            S1RBZC9iVk1zK29XU0VDQ0UyeTh0cTY3SFZVClZ0NzNXY3duZGJXd01TVTlNNU56
            ZUtFalhueWpwUGJ2My9hK29odURZY2sKLS0tIE9razhCS3E3OG9EczdPVWE5bTVz
            RXJybmpuNDI0SzlsVDM5ZSswcEJlNWcKYD55OK8X9J0fdTCbcNQdNjzbLYeQHHeA
            rA20u8IBV9vsILmokXMvFmezeDI9ozm2FT4RYBCC/cxVPNXzkL042Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T04:33:29Z"
    mac: ENC[AES256_GCM,data:59l2EwAbmGkNcpESyeigb2iJO9fA4HpIErSsXNxk7BYhgT5aNY/1ghJKqiUOItV/8f5E9Tb+iown1RwZECzog/ElqqhGImGuyIr47e9YYnpU28L37/lrHrG1EusYc08fUVUHXCo/4T29CIFCF57hwc6DOs7UP2NJzQCwtGFR8o4=,iv:JAEXN55KbbYXzI09LbNNDk3R8kdfApdnMaKxZx1+HM4=,tag:5IIPLKSDs/+8R8aqnCvteA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
