---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wizarr

spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      wizarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository:  ghcr.io/wizarrrr/wizarr
              tag: 4.1.1@sha256:52df19ffa3d4f59e9abc865032bc51c3afd077a88d5a6d50ba4a81d0e8582d9e
            env:
              TZ: ${TIME_ZONE}
              APP_URL: https://invite.${SECRET_DOMAIN_MEDIA}

            resources:
              requests:
                cpu: 15m
                memory: 180M
              limits:
                  memory: 300M
    service:
      app:
        controller: wizarr
        ports:
          http:
            port: 5690
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN_MEDIA}"
        className: internal
        hosts:
          - host: &host "invite.${SECRET_DOMAIN_MEDIA}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN_MEDIA/./-}-production-tls
    persistence:
      config:
        existingClaim: wizarr
        globalMounts:
          - path: /data/database
