---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: email-oauth2-proxy-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        OUTLOOK_ADDRESS: "{{ .STALWART_OUTLOOK_ADDRESS }}"
        OUTLOOK_OAUTH_CLIENT_ID: "{{ .STALWART_OUTLOOK_OAUTH_CLIENT_ID }}"
        OUTLOOK_OAUTH_CLIENT_SECRET: "{{ .STALWART_OUTLOOK_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - find:
        name:
          regexp: ^STALWART_OUTLOOK.*
