---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
  volume.beta.kubernetes.io/mount-options: "nfsvers=3,nconnect=8,nolock,soft,noatime,nodiratime"
spec:
  storageClassName: "${VOLSYNC_STORAGECLASS:-zfs-backed-pvs}"
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-dst"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-5Gi}"
