kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  ingress-template: |
    . . .
    # handling custom.nginx.org/rate-limiting` and custom.nginx.org/rate-limiting-rate

    {{if index $.Ingress.Annotations "custom.nginx.org/rate-limiting"}}
    {{$rate := index $.Ingress.Annotations "custom.nginx.org/rate-limiting-rate"}}
    limit_req_zone $binary_remote_addr zone={{$.Ingress.Namespace}}-{{$.Ingress.Name}}:10m rate={{if $rate}}{{$rate}}{{else}}1r/s{{end}};
    {{end}}

    . . .

    {{range $server := .Servers}}
    server {

      . . .

      {{range $location := $server.Locations}}
      location {{$location.Path}} {

        . . .

        # handling custom.nginx.org/rate-limiting and custom.nginx.org/rate-limiting-burst

        {{if index $.Ingress.Annotations "custom.nginx.org/rate-limiting"}}
        {{$burst := index $.Ingress.Annotations "custom.nginx.org/rate-limiting-burst"}}
        limit_req zone={{$.Ingress.Namespace}}-{{$.Ingress.Name}} burst={{if $burst}}{{$burst}}{{else}}3{{end}} nodelay;
        {{end}}

        . . .
