---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app resume
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      resume:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dapperdivers/developer-portfolio:sha-283c2fb2f72840bc53c100896955dae22e0709a1
            env:
              ALLOWED_DOMAINS: ${SECRET_DOMAIN_PERSONAL}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 3001
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 5Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3001
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_PERSONAL}"
        className: external
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN_PERSONAL}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: "www.${SECRET_DOMAIN_PERSONAL}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: "${SECRET_DOMAIN_PERSONAL}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: ${SECRET_DOMAIN_PERSONAL/./-}-tls

