---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: finance-postgres-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: finance-postgres-superuser
  dataFrom:
    - find:
        name:
          regexp: ^POSTGRES_SUPER_
