---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr-node
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: storage
  values:
    controllers:
      tdarr-node:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            nvidia.feature.node.kubernetes.io/gpu: "true"
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr-node
              tag: 2.37.01@sha256:7e9d8e4c6520c3865387565b0cb9744f7dafb79b594fcd88c2ad93d5ad001e37
            env:
              TZ: ${TIME_ZONE}
              NVIDIA_DRIVER_CAPABILITIES: all
              NVIDIA_VISIBLE_DEVICES: all
              nodeName: P100
              inContainer: true
              ffmpegVersion: 7
            probes:
              liveness: &probes
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 150
        fsGroup: 140
    service:
      app:
        controller: tdarr-node
        ports:
          server:
            enabled: true
            protocol: TCP
            port: 8266

    persistence:
      config:
        existingClaim: *app
      media:
        type: nfs
        server: openmediavault-used.manor
        path: /Used
        globalMounts:
          - path: /media
      transcode_cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 40Gi

