---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-service.yaml
  - main-api.yaml
  - user-org-service.yaml
  - file-service.yaml
  - transaction-service.yaml
  - ai-service.yaml
  - categorization-service.yaml
  - frontend.yaml
