---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: finance-user-org-service
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
  values:
    controllers:
      finance-user-org-service:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/chelonianlabs/finance-user-org-service
              tag: latest
            env:
              HOST: "0.0.0.0"
              PORT: &port "8002"
              AUTH_SERVICE_URL: "http://finance-auth-service.chelonian.svc.cluster.local:8001"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: finance-app-secret
                    key: USER_ORG_DATABASE_URL
              API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: finance-app-secret
                    key: API_KEY
            probes:
              readiness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 30
              liveness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile: { type: RuntimeDefault }
      imagePullSecrets:
        - name: ghcr-chelonian
    service:
      app:
        controller: finance-user-org-service
        ports:
          http:
            port: *port
