apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:p5xdmGuXBuL+fzkCHqpD53IgBXULpd/pID/zffVhkHNw1EVy,iv:3PdJLcp2nWaxsSaSRIek4mdrrOn0r1HBdnPBb8WjnAc=,tag:C9hG+nzfcglXHsvKNXH0cw==,type:str]
    credentials.json: ENC[AES256_GCM,data:DMSRX3nvid3M5wRnrev43HpJ8QDAOzz0e983pISRomV6pqMBijvA2uKRufwM/iNSS0dus020qkkvKTuw0/gcipDMFixc3cFhe+rPzvB4RdWmCbhX6rLsO3kmuRcHEjlhzV2NEJ4/mr5t12BfXJqNaZiURTH6kMPkl8aAIJLDV27Qy/yxwh/xC9C1COyxAhOfn6C5malNhJXgLV2NgmcApy+CRb8bU4dHsiySh5bmwQ==,iv:1TlWSdL9ijffArS2t8/pFkqFatyoIr+EEfTmfna/tj4=,tag:7GU5xJpJ4FPk83g/8O3Yhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcTNRdldtaGpVVFpqOHE4
            T0JDRk90V2tENHVmdkhDVjc4bTVTdEo2RFZnCjhSZDY4eFhNc3VOMUxCRmRZK2tn
            a1gzbFVtM28rVEZjK3dndGpjZ25xSWcKLS0tIFpXOHBGayt2OTFOOCt6NXBDTThh
            Wnd4RnYvUFQ1c05NbFdEK2FHbDRZZkUK0/vZ59BXjO6ZestZ+9vNSYvIfP7Tz7tk
            W0NvRDwcZU1GzfIKgv0MQL3J9a3D5fac5mcqxl+4o/fq4375HaBoWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T14:43:53Z"
    mac: ENC[AES256_GCM,data:je5XylZgxFQ7Vy+TPnicj1xSc7AO+JPFfzws91mPjZoTGRTQ23WOHtJ8RtQNij2/HROZrjuQ9qygFhmtUaoXoWqOwzVrc2h75nASG9YrDU3V8dtZ6XF88zYRUyXPwgNNkOkhvrO+e9lsYsv2eMIjCmSjTlCxL5l3APWHtpe+XzA=,iv:gJC17b9md7qqW1CCr4OVJHo1vH+X1i8UUTsgMLmTsb0=,tag:/KaTU74IKotmqtjABY3zew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
