apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/SKe9Hqnb/vh5WWPW5pOK/Cn/7y+LBeC9zs087yXHOsWE8GP,iv:kjxWggcDC0Xxi4fpFGs+cofxJHW1YtLm4IHa1AQbxPc=,tag:SBwOdC4jFh9rFc4QVyA1ow==,type:str]
    credentials.json: ENC[AES256_GCM,data:LBlET+atqbvKm38kMgMabzixUGah+kudw+/OKxvQ5d5Tsh9ICnZ0JXJQT0s9aa8PiGqlKrlCfO/QSIteABvVoD2itZsaXZwXLMeKNTiSpDWnZyq4/sOPcI1H0IvKdRcc+yKtUmyDf3lS1YgJ1ihkq9QDEtr8DntmwOdm+HKbZ0iNRrt/j/Cii0QCCVvi9XMrleiciTYx/KcpkOM+MM5s7+TzdPELh9I87qOJG7om/w==,iv:pipgr1Vc/NuchvYGVnpixRhLVZkdYlcHr+9CPnnW8cE=,tag:8ge6oA5KnvMtjpRDcWWBiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d3hUbjRnYlNaVVg3UERF
            OGlGRXh5WjJEaW5jZjBRUXM4cTRBcDh6L0ZVCnJTNHhXdEtNNk9BQlRIcmc4ZWtV
            MEF4bXFGZnhMcVhxVWlQWEpSVzNlK2MKLS0tIHM5OURmSnBWbnBNSUp4Yjg4Sndq
            Q2tVanNEMk5pbHlzQm5rbHF3aytCelEKyfG1nIIsaB1IQ/p8MEty+4v5j7vlBeCi
            y6SsIiDDgDYhqA/JEng6Sp6grF/FOcgBiInirSBUrXCjpp/1hGkc2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T16:04:35Z"
    mac: ENC[AES256_GCM,data:9U6wjeobU3bQECY2RjP+eUlMT5w+DrMERCadeiky9BHSZLUHdEiBFMwExAqtw/1/SWUuoegSczoPFMk4io7p6q5w5jdfFD1h7DFzqdRIMDdGble63LQ5a8byOZ06Fh4v4t8vN2eD8XWZeDeYxSOFshMXrML3jgr+Ef0HYVuhLDw=,iv:vHhzrDbl2lcX2JLPBiWjINqYd5uIlu5Gco1pq30M8AE=,tag:OIJzSWnVNnYj+HtWH6incw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
