apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:adJDwRC+rXPF6elVPNhXu0NObFOPmZKAZfbB3MoFTwo=,iv:2y7c2p9/VIvFPldOrZeUYiHK8/ROtjmrKeyd9ELxPGo=,tag:yWnVMlNIbq3rMFuijL0z9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cXVZakpSMXl3WlhaVnhX
            aDEwdmV4N2FSbnc4Z2toZ091a05MTWpNWVg0ClhvVXFhRFNDRFJhVldsTUxhYU5z
            ZWpMN3l1ZWVUVzJwYnhJWjBISk1rNEEKLS0tIEJkdEJqR053ZkRKaDhBSGhYeGwz
            cW5iYmpKeVNBb3B5ZGFEUTYzY29tYUkKE63MfpDNQLXfC5Af57FJ9bkAFv8set0E
            mgAh3oBvrdKN47BSRLLVmnF2lFzbWKfx3xjVk9ijtxl+j0To7cHD3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T01:38:39Z"
    mac: ENC[AES256_GCM,data:I3c29G1/jTN7v0eYfw6ZFdib8iKXh3ZOoXJPiXDziCMC72QPTMT0y5s10hi7BWQyf3DBd1jbCiMNYEeB7PVxtTFw/gOyBtoYmhYB4G8o52/L1XpjSfDRPDRhXYywsEo5kIeirEgFnhUSt7S3KPbBfpSLjIAOGyyuliqq0PdmCrE=,iv:Os7Z1xHHqjbltBgETLevseytIrJd2i7/yVdejwhuC3w=,tag:MP3hJAoTLSaRqtIoTC3GKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
