apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:m3N5jpiUJM8OoElmTM+QclBmkB1GTQzKSqjQQnvygOw=,iv:eke00xKHPrfRMlT73fWen6EkgtBLuAhFuMi3r+Qp3Wg=,tag:uHFr0bi1W7elqMFw+ruYvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZzJrNnRNMFRxbFNTYUo2
            ZWhFZzZEa3Q1NGtvN0kwMk56NlpISC9yRzM0CmM3d0kyLzgyNlcrZW53d3JQcUkw
            aDdBbHBBQUVzLzdlRXc1R0YzNU43ZDgKLS0tIGdHRVNLMzQxTUgwYlp3LzdkRkp6
            dmN2OUVHQnlwOTQ3MllET09hTGdYWjQKzfkncpy7XVVH2RV9PEhwCIHwGwavHa2x
            huQH0buU5QXdjavlo1gJRB+ZD/qfJ8QQ108xM6Hn4MLAQkqI8i7zeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T04:33:29Z"
    mac: ENC[AES256_GCM,data:O99VzQc7MjGINDqoe8I8DFq1V/f3wW/pyNJTCyjehskR8P3dwwpKEHtzY0Xpxr1pj4ntf2lznIvsm0jEGZf28pewqzo3Yy7TD+OmMbrnS0TrYHiNmND4ZCl/YxjEj9g7BT3Fd5ZOEoEgnBHP/gFpNhJfjoNpfsrscwqlf9YvOt4=,iv:KISE5pn3YcrJUoN4cWASF7x/88vz6wD0gQnZYDeDECI=,tag:s7zgaqHAsmWTep2f7vx0mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
