apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:f2nRjJLt5lKU3WQuIfPgPn7S3ZeUoPQE0WI+dx8Lx9k=,iv:32+VWkF0UoiIMWveXAxVX2XGPzx5EaN8DkMKaqZiAGU=,tag:h4I/ZR1J3uJBjtBV1f2r5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINnQ0RzdacHpyTkljNzAy
            YmJjODUra3MrSisrWWcraS9EUXpFNHUyTUdRCkVSOTJUcWlNeUlBWXRrZ2tTSVQ2
            WW5tZ3ovOGFhOUZ1YmhZSlpBbUYvOEUKLS0tIGlQc1hGdGgwMW5aODFGZ0xnclBV
            cTlRRWFKWEhUYmpoU2pHUTdiNmdubDgK6kDdMUoq+qFsS4WKwWbZAt2oVF+ygD2N
            A1FRMoWDZlMGqAwMe1Drk7A5CD41qWrSpTwzwIlBZFaxJyCDaI06+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T03:05:26Z"
    mac: ENC[AES256_GCM,data:ns3VK7GCCZ+Gsqm78Zz4UuT2qX2ExlM6TU/qEacyao+38kTFNb1uIAsKGZklVNqa7414HN2k80AOBeoUqHY6iGYgs0uYLsEU2fVoOcioUKSNi5CnqWweYIzfQJcpG+nGwHgJpbO4Ke5C8gF25zSBTa96jIf2Vog+wFv7vwDI4Mk=,iv:2ixVr9KtGV77iNbtNPLVybZdi4+0jJzaXQu9m51SqyM=,tag:1swrtkChsc0IGqDBjLrzNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
