---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: "${SECRET_DOMAIN/./-}-staging-tls"
  data:
    - secretKey: tls.crt
      remoteRef:
        key: Certificates/${SECRET_DOMAIN/./-}/tls.crt
    - secretKey: tls.key
      remoteRef:
        key: Certificates/${SECRET_DOMAIN/./-}/tls.key
