---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: "${SECRET_DOMAIN/./-}-staging-tls"
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .MINIO_ROOT_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"

  dataFrom:
    - find:
        path: MINIO_ROOT_USER
    - find:
        path: MINIO_ROOT_PASSWORD

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_MEDIA/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN_MEDIA/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_MEDIA}"
  dnsNames:
    - "${SECRET_DOMAIN_MEDIA}"
    - "*.${SECRET_DOMAIN_MEDIA}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_PERSONAL/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN_PERSONAL/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_PERSONAL}"
  dnsNames:
    - "${SECRET_DOMAIN_PERSONAL}"
    - "*.${SECRET_DOMAIN_PERSONAL}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_DIVING/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN_DIVING/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_DIVING}"
  dnsNames:
    - "${SECRET_DOMAIN_DIVING}"
    - "*.${SECRET_DOMAIN_DIVING}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_WIFE/./-}-staging"
spec:
  secretName: "${SECRET_DOMAIN_WIFE/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_WIFE}"
  dnsNames:
    - "${SECRET_DOMAIN_WIFE}"
    - "*.${SECRET_DOMAIN_WIFE}"

