---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: infisical-push-secret-demo
  spec:
    resyncInterval: 1m

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: Retain # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: homelab-p-iqd
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        secretName:  "${SECRET_DOMAIN/./-}-staging-tls"
        secretNamespace: cert-manager

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
