---
  apiVersion: secrets.infisical.com/v1alpha1
  kind: InfisicalPushSecret
  metadata:
    name: "${SECRET_DOMAIN/./-}-staging-tls"
  spec:
    resyncInterval: 1m
    hostAPI: https://app.infisical.com/api

    # Optional, defaults to no replacement.
    updatePolicy: Replace # If set to replace, existing secrets inside Infisical will be replaced by the value of the PushSecret on sync.

    # Optional, defaults to no deletion.
    deletionPolicy: None # If set to delete, the secret(s) inside Infisical managed by the operator, will be deleted if the InfisicalPushSecret CRD is deleted.

    destination:
      projectId: homelab-p-iqd
      environmentSlug: prod
      secretsPath: /Certificates
    push:
      secret:
        name: ${SECRET_DOMAIN/./-}-staging-tls"
    template:
      engineVersion: v2
      data:
        tls.crt: '{{ index . "tls.crt" | b64enc }}'
        tls.key: '{{ index . "tls.key" | b64enc }}'
    data:
      - match:
          secretKey: &key tls.crt
          remoteRef:
            remoteKey: ${SECRET_DOMAIN/./-}-staging-tls"
            property: *key
      - match:
          secretKey: &key tls.key
          remoteRef:
            remoteKey: ${SECRET_DOMAIN/./-}-staging-tls"
            property: *key

    authentication:
      universalAuth:
        credentialsRef:
          secretName: infiscal-auth-secret
          secretNamespace: external-secrets
