---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-dcgm-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  interval: 30m
  path: ./kubernetes/main/apps/observability/exporters/dcgm-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: node-feature-discovery
