apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: selfhosted
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: open-webui
    template:
      engineVersion: v2
      data:
        OAUTH_CLIENT_ID: "{{ .OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OAUTH_CLIENT_SECRET }}"
        OPENID_PROVIDER_URL: "{{ .OPENID_PROVIDER_URL }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"

  dataFrom:
    - find:
        path: OAUTH_CLIENT_ID
    - find:
        path: OAUTH_CLIENT_SECRET
    - find:
        path: OPENID_PROVIDER_URL
    - find:
        path: OPEN_WEBUI_SECRET_KEY
