apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4WLzZmrhy8Od+u7p+s24qa6jJUVEZHWSKhGU59WCQa6FGqWB3/kZow==,iv:enzgNEIJwSLKXVkE9bb428CQXjscG/5bdtSRWdlRqUI=,tag:P8ofqwlb7Su6gahCvWZkxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j6u0d4jpxu9nf3y77trs9pzde7jxurjjxzvw7p6rvfykf5n4jv6sh3gyd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQTVIYTg5bkFzTHhPUDd4
            UDQ1bWczTGlCNzZoc0lwaE5TQnBVV2x3T0QwCnRYcFN2ZDgrNm5DQWJGUjJhK2g1
            UlkvRkEwby9PVW1EUUZxd2g5L0RBTVUKLS0tIHpzaVVubXFlbk1ZTXpzVDRWa3p3
            YW1KUW52SW51VG51Vk14dnIvNGhzTGMKB7Tdejq1oMaaRY+7SVNUFNlGRKuLkXRS
            uOvOjsta0aY0CbiHjGIP3zEbujeiqjqxozyxdfXpKPok1mUsQeWX5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T21:52:51Z"
    mac: ENC[AES256_GCM,data:Veizpv8lNWFtChEXhy41pf4SuO2enal0Y3jlnbL4mb01VsWKzXpFag324vaxFHmFEYn4+G30GAcocUNk3XD9xQ5/hjgqJPJ+mL5V9t3+IwUV5cCQSyQVO0iQU9RNU5V7LcLSLrUXLETMsxE+ph+kVO9H90Q4YjLJwyL/HeUqJuY=,iv:vTxs36I0PrGtPDP2WC0fUNA+WbfzDyWY0Jac6/ceQf0=,tag:MrMhzqj6hsqjhkL9srpt5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
