apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4WfwgTiq1b7KsVAWVDmRhsEaAIiNgsCixD6TgEtYqEWTXPY6uq8Fsw==,iv:4wAi0f5TssAVnfEqxtlvC5hArydIhI6AvLUVTXB135c=,tag:LM/EQC66zVwEIqE9H4/Z0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVGk2TFRKeU1QaW9JM3oy
            ejlVRDdjTlhRaFlCMTQxNTVWaGlJNFBPQ0NNCmdTQjhiUEtLK21QK2VkRk5RL0Vu
            YVhFcWJpalNjY0JtekxaeForQksxZGsKLS0tIGd4UURSbU5xK0x4RE1XMmF2RUVJ
            YzFOUGthRnRSSnBtcVh4SStnOUdiS2MKOaUJXSVvl+6Pen0PPvpohTeCZuaN5Ltj
            TLRyCUmQZsFKRKfZxbkUzuwwE/M9tb+kJsfZUb78wQM7vJ8wUHnVmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T01:38:39Z"
    mac: ENC[AES256_GCM,data:ATmfDxV/W+R6S7hJNGZLg7qieGfCn381h5MBhRl4Pf8zqA2YUGypF1NoeaA1OeQKmMsu/9Po0TLdWXNEKgyNpfqUnL8Xohiq/i6nqgMBDSL+mqjllLVoFN4DzKLYfBd7X2i3PlibLdv7rYrOtnUjbVziDxCKCMoSQmxy0NdEF+s=,iv:81k1DOTmmm2LKyCAK0tRPbErDXZhzeyw5tnHzvjiTao=,tag:9oRtc5j4UnOZoJ5tximHUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
