apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:AC4XcPV3gGSEqP8YKjfeFWMGjuipMfNjK5Ky7NxDUO8lmPYwmtMvOw==,iv:DsicK00eW8toTHlkZtqhIm0NEqvgxTndyTF1pQi1JGQ=,tag:rzNr6SY3bqQhLEOH/unHEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxsqzck5798q4ye0f3cyx94pjwdxqa00qw57gs6ckh2vpljxzelqs9kenx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcjVZM0htVUUxOVN5aGdY
            aVZpb1NaNWtBckxqbzAxeEorRmwzYTdwMVdNCjFXQklEZEpFTjYrL1ZBeUhQYlh0
            QThpcHFLYUxjeEVqODV5WjF0Q2ZKbzAKLS0tIHcwYlJSdi9UMXI0bHJaRnJ0NXJW
            M3pvM2VCKzZ0emV0anJxU0JjclJlcDgKnVbB35vCHTRME20rp0l/l0IeDa0XfVz3
            VDcMU1M+X7cphZxap1j76MJY9AAjNpW7hk13Q0JAeu87oX/b+vR4Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-26T04:33:29Z"
    mac: ENC[AES256_GCM,data:L4/TpyVcyLrz2IxEs3uY6mEXHsOIDB6CBwosxR/fqB/XNW+xLUpfbYq2dnpGvKtuwxkqVhD+3MLADfihWQ+yeEvwyNQnrNh0Mmc9CvUnR6V7yDOzESxi7HQPnir+0RvITmeUM6B1lSEnHeAmDsD+DT0mZ7DLfkwCXZXET1u0kRU=,iv:Qj7SRjNe7uiJVzmQ2Ha9nGwAVP4hR9xntLv1vRNEq/s=,tag:KTQZmxvgsal365F0bIf0kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
