# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bedivere
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: bedivere-secret
    template:
      engineVersion: v2
      data:
        HOMEASSISTANT_TOKEN: "{{ .MOLT_HOMEASSISTANT_TOKEN }}"
  dataFrom:
    - find:
        name:
          regexp: ^MOLT_HOMEASSISTANT.*
