---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dagonet-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: dagonet-secret
    template:
      engineVersion: v2
      data:
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - find:
        path: AI/LiteLLM
        name:
          regexp: "^LITELLM_MASTER_KEY$"
