---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: galahad
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: galahad-secret
    template:
      engineVersion: v2
      data:
        OPENCTI_TOKEN: "{{ .OPENCTI_ADMIN_TOKEN }}"
        SHODAN_API_KEY: "{{ .SHODAN_API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ^(OPENCTI|SHODAN).*
