---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudflare-ddns-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ACCOUNT_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"

  # TODO: move from sops to here as well
  dataFrom:
    - find:
        path: CLOUDFLARE_API_KEY
