---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: vaultwarden-secret
    template:
      engineVersion: v2
      data:
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: vaultwarden
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-postgres
  target:
    name: vaultwarden-db-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-vaultwarden
