---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../flux/components/alerts
  - ../../flux/components/namespace
  - ../../flux/components/sops
  - ../../flux/components/substitutions
resources:
  - ./csi-driver-nfs/ks.yaml
  - ./volsync/ks.yaml
  - ./minio/ks.yaml
