---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nut-upsd
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/kube-system/nut-upsd/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
